#!/bin/bash
model3com=$(snmpwalk -v 1 -c recia-ro $1 1.3.6.1.2.1.1.1.0 | cut -d'"' -f2 | head  -n1 | awk '{print $1 $3}')
model=$(snmpwalk -v 1 -c recia-ro $1 1.3.6.1.2.1.1.1.0 | cut -d'"' -f2 | head  -n1 | awk '{print $1;}')

if [[ "$model" == "H3C" ||  "$model" == "Cisco" || "$model3com" == "3Com4500" ]]; then
	./tg-telnetv2 $1 Username
fi

if [ "$model3com" == "3Com3" ]; then
        ./tg-telnetv2 $1 Login
fi
