#!/bin/bash
#set -o nounset
#set -o verbose
######## Declaration des variables ########
export RTUSER=njoubert
export RTPASSWD=ninja21
export RTSERVER=https://rt.giprecia.fr/rt/

OPTERR=0 #Permet d'eviter le message d'erreur de getopts
day=$(date "+%d/%m/%Y")
fday=$(date "+%d-%m-%Y-%H-%M")
sday=$(date "+%Y-%m-%d")
listStatus="open stalled resolved rejected"
expor="false" #Permet d'activer la fonction export
debug="false" #Permet d'activer le debug des requetes
oTg="(Owner = 'cblondeau' OR Owner = 'njoubert' OR Owner = 'ssanchez' OR Owner = 'dgelve' OR Owner = 'lleminoux' OR Owner = 'cfonck' OR Owner = 'stellier')"
cTg="(Creator = 'cblondeau' OR Creator = 'njoubert' OR Creator = 'ssanchez' OR Creator = 'dgelve' OR Creator = 'lleminoux' OR Creator  = 'cfonck' OR Creator = 'stellier')"
oRecia="(Owner = 'apaillard' OR Owner = 'anombret' OR Owner = 'aguevara' OR Owner = 'cjullien' OR Owner = 'cdaviau' OR Owner = 'cdubreuil' OR Owner = 'dgombault' OR Owner = 'fenard' OR Owner = 'cat' OR Owner = 'jgribonvald' OR Owner = 'kdeschamps' OR Owner = 'kfrapin' OR Owner = 'ngomes' OR Owner = 'pmontagne' OR Owner = 'sgautier')"
cRecia="(Creator = 'apaillard' OR Creator = 'anombret' OR Creator = 'aguevara' OR Creator = 'cjullien' OR Creator = 'cdaviau' OR Creator = 'cdubreuil' OR Creator = 'dgombault' OR Creator = 'fenard' OR Creator = 'cat' OR Creator = 'jgribonvald' OR Creator = 'kdeschamps' OR Creator = 'kfrapin' OR Creator = 'ngomes' OR Creator = 'pmontagne' OR Creator = 'sgautier')"
cBot="(Creator = 'reciabot' OR Creator = 'root')"
cOther="(Creator != 'cblondeau' AND Creator != 'njoubert' AND Creator != 'ssanchez' AND Creator != 'dgelve' AND Creator != 'lleminoux' AND Creator != 'cfonck' AND Creator != 'stellier' AND Creator != 'apaillard' AND Creator != 'anombret' AND Creator != 'aguevara' AND Creator != 'cjullien' AND Creator != 'cdaviau' AND Creator != 'cdubreuil' AND Creator != 'dgombault' AND Creator != 'fenard' AND Creator != 'cat' AND Creator != 'jgribonvald' AND Creator != 'kdeschamps' AND Creator != 'kfrapin' AND Creator != 'ngomes' AND Creator != 'pmontagne' AND Creator != 'sgautier' AND Creator != 'reciabot' AND Creator != 'root')"


#Coloration
VERT="\\033[1;32m"
NORMAL="\\033[0;39m"
ROUGE="\\033[1;31m"
ROSE="\\033[1;35m"
BLEU="\\033[1;34m"
BLANC="\\033[0;37m"
BLANCLAIR="\\033[1;08m"
JAUNE="\\033[1;33m"
CYAN="\\033[1;36m"


####### Gestions des dates ##############

formatDate(){

CURRENTMONTH=$1
CURRENTYEAR=$2

ARRAYMONTHS=(Janvier Fevrier Mars Avril Mai Juin Juillet Aout Septembre Octobre Novembre Decembre)


if [ ${CURRENTMONTH:0:1} != 0 ] # On verifie que le mois est renseigne avec un zero
	then
	if [ $CURRENTMONTH -lt 10 ]
		then CURRENTMONTH="0"$CURRENTMONTH # Permet d'ajouter le zero du mois si celui n'est pas deja renseigne
	fi
fi

LASTDAY=$(cal $CURRENTMONTH $CURRENTYEAR | egrep "28|29|30|31" | tail -1 | awk '{print $NF}')
FIRSTDAYMONTH=$CURRENTYEAR"-"$CURRENTMONTH"-01"
LASTDAYMONTH=$CURRENTYEAR"-"$CURRENTMONTH"-"$LASTDAY
NAMEMONTH=${ARRAYMONTHS[$1-1]}
}

usage(){
    echo "Usage: $0 -m -a [options]"
    echo "--help ou -h : afficher l'aide"
    echo "--version ou -v : afficher la version"
    echo "--mois ou -m : le mois choisi format numerique (ex: 1 pour janvier, 2 pour fevrier etc)"
    echo "--annee ou -a : l'annee choisi format long (ex: 2014)"
    echo "--debug ou -d : permet d'afficher les requetes utilises"
    echo "--export ou -e : export en csv les donnees avec le nom de fichier suivant [copil-mois-annee.csv]"
}

dump(){
        #Supprime la coloration pour sortie dans un fichier
        traitement | sed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[mGK]//g"
}

export(){
tmpfile=$(mktemp)
destination="/home/ftp/share/Copil"
        #Supprime la coloration pour sortie dans un fichier
        traitement | tee $tmpfile
	formatDate $month $year
	echo
	if [ -f copil-$NAMEMONTH-$CURRENTYEAR.csv ]; then
		filetime=$(stat -c '%.19z' copil-$NAMEMONTH-$CURRENTYEAR.csv | sed 's/[[:space:]]/_/g' )
		echo -e "$ROUGE""Attention - Le fichier "copil-$NAMEMONTH-$CURRENTYEAR.csv" existe""$NORMAL"
		mv copil-$NAMEMONTH-$CURRENTYEAR.csv copil-$NAMEMONTH-$CURRENTYEAR-$filetime.csv
		echo -e "Le fichier copil-$NAMEMONTH-$CURRENTYEAR.csv a ete renomme en copil-$NAMEMONTH-$CURRENTYEAR-$filetime.csv \t ["$VERT"OK"$NORMAL"]"
	fi 
        	cat $tmpfile | sed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[mGK]//g" | sed -r "s/:/;/g" >> copil-$NAMEMONTH-$CURRENTYEAR.csv
		echo -e "Creation du fichier copil-$NAMEMONTH-$CURRENTYEAR.csv \t ["$VERT"OK"$NORMAL"]"
        rm -f $tmpfile
        if [ -d "$destination" ]; then
                echo "Copie du fichier copil-$NAMEMONTH-$CURRENTYEAR.csv dans $destination"
                cp -p copil-$NAMEMONTH-$CURRENTYEAR.csv $destination
        fi

}

traitement(){
	formatDate $month $year
	echo -e $ROSE"Copil de : "$NAMEMONTH $CURRENTYEAR"$NORMAL";
	total
	file '02 - Incidents'
       	file '02.1 - Incidents ProActifs'
        file '03 - SFR (Incidents)'
        file '04 - Travaux Niveau I'
       	file '05 - Travaux Niveau II'
}

total(){
	echo -e $BLANC"Nombre ticket cree pour toute les files"$NORMAL;	
	# Total de ticket cree
	request="Created >='$FIRSTDAYMONTH' AND Created <='$LASTDAYMONTH'" # on créé une variable car on a besoin à plusieurs endroits
	if [ "$debug" == "true" ]; then
		query="$VERT : Requete => \"$request\""
	else
		query=""
	fi
	echo -e "$VERT""Total : "$ROUGE"$(rt ls -i "$request" | grep ticket -c)"$query"$NORMAL";
	unset request # on detruit la variable pour eviter les problemes

	# Total de ticket cree par la tg
	request="$cTg AND Created >='$FIRSTDAYMONTH' AND Created <='$LASTDAYMONTH'" 	
        if [ "$debug" == "true" ]; then
                query="$VERT : Requete => \"$request\""
        else
                query=""
        fi
	echo -e "$ROSE""Total pour la telegestion : "$ROUGE"$(rt ls -i "$request" | grep ticket -c)"$query"$NORMAL";
	unset request

	# Total de ticket cree par le giprecia
	request="$cRecia AND Created >='$FIRSTDAYMONTH' AND Created <='$LASTDAYMONTH'"
        if [ "$debug" == "true" ]; then
                query="$VERT : Requete => \"$request\""
        else
                query=""
        fi
	echo -e "$JAUNE""Total pour le giprecia : "$ROUGE"$(rt ls -i "$request" | grep ticket -c)"$query"$NORMAL";
	unset request

        # Total de ticket cree par reciabot
	request="$cBot AND Created >='$FIRSTDAYMONTH' AND Created <='$LASTDAYMONTH'"
        if [ "$debug" == "true" ]; then
                query="$VERT : Requete => \"$request\""
        else
                query=""
        fi
        echo -e "$BLEU""Total cree automatiquement (reciabot + root) : "$ROUGE"$(rt ls -i "$request" | grep ticket -c)"$query"$NORMAL";
	unset request

        # Total de ticket cree par les admins
	request="$cOther AND Created >='$FIRSTDAYMONTH' AND Created <='$LASTDAYMONTH'"
        if [ "$debug" == "true" ]; then
                query="$VERT : Requete => \"$request\""
        else
                query=""
        fi
        echo -e "$CYAN""Total pour les admins : "$ROUGE"$(rt ls -i "$request" | grep ticket -c)"$query"$NORMAL";
	unset request

	echo
        echo -e $BLANC"Nombre ticket resolu pour toute les files"$NORMAL;

        # Total de ticket resolu
	request="Resolved >='$FIRSTDAYMONTH' AND Resolved <='$LASTDAYMONTH'"
        if [ "$debug" == "true" ]; then
                query="$VERT : Requete => \"$request\""
        else
                query=""
        fi
	echo -e "$VERT""Total : "$ROUGE"$(rt ls -i "$request" | grep ticket -c)"$query"$NORMAL";
	unset request

        # Total de ticket resolu par la telegestion
	request="$oTg AND Resolved >='$FIRSTDAYMONTH' AND Resolved <='$LASTDAYMONTH'"
        if [ "$debug" == "true" ]; then
                query="$VERT : Requete => \"$request\""
        else
                query=""
        fi
        echo -e "$ROSE""Total pour la telegestion : "$ROUGE"$(rt ls -i "$request" | grep ticket -c)"$query"$NORMAL";
	unset request

        # Total de ticket resolu par le giprecia
	request="$oRecia AND Resolved >='$FIRSTDAYMONTH' AND Resolved <='$LASTDAYMONTH'"
        if [ "$debug" == "true" ]; then
                query="$VERT : Requete => \"$request\""
        else
                query=""
        fi
        echo -e "$JAUNE""Total pour le giprecia : "$ROUGE"$(rt ls -i "$request" | grep ticket -c)"$query"$NORMAL";
	unset request

        # Total de ticket resolu en nobody
	request="Owner = 'nobody' AND Resolved >='$FIRSTDAYMONTH' AND Resolved <='$LASTDAYMONTH'"
        if [ "$debug" == "true" ]; then
                query="$VERT : Requete => \"$request\""
        else
                query=""
        fi
        echo -e "$BLEU""Total pour Nobody : "$ROUGE"$(rt ls -i "$request" | grep ticket -c)"$query"$NORMAL";
	unset request

	echo
        echo -e $BLANC"Nombre ticket pere resolu pour toute les files"$NORMAL;

        # Total de ticket pere resolu
	request="MemberOf IS NULL AND Resolved >='$FIRSTDAYMONTH' AND Resolved <='$LASTDAYMONTH'"
        if [ "$debug" == "true" ]; then
                query="$VERT : Requete => \"$request\""
        else
                query=""
        fi
        echo -e "$VERT""Total : "$ROUGE"$(rt ls -i "$request" | grep ticket -c)"$query"$NORMAL";
	unset request

        # Total de ticket resolu par la telegestion
	request="MemberOf IS NULL AND $oTg AND Resolved >='$FIRSTDAYMONTH' AND Resolved <='$LASTDAYMONTH'"
        if [ "$debug" == "true" ]; then
                query="$VERT : Requete => \"$request\""
        else
                query=""
        fi
        echo -e "$ROSE""Total pour la telegestion : "$ROUGE"$(rt ls -i "$request" | grep ticket -c)"$query"$NORMAL";
	unset request

        # Total de ticket resolu par le giprecia
	request="MemberOf IS NULL AND $oRecia AND Resolved >='$FIRSTDAYMONTH' AND Resolved <='$LASTDAYMONTH'"
        if [ "$debug" == "true" ]; then
                query="$VERT : Requete => \"$request\""
        else
                query=""
        fi
        echo -e "$JAUNE""Total pour le giprecia : "$ROUGE"$(rt ls -i "$request" | grep ticket -c)"$query"$NORMAL";
	unset request

        # Total de ticket resolu en nobody
	request="MemberOf IS NULL AND Owner = 'nobody' AND Resolved >='$FIRSTDAYMONTH' AND Resolved <='$LASTDAYMONTH'"
        if [ "$debug" == "true" ]; then
                query="$VERT : Requete => \"$request\""
        else
                query=""
        fi
        echo -e "$BLEU""Total pour Nobody : "$ROUGE"$(rt ls -i "$request" | grep ticket -c)"$query"$NORMAL";
	unset request
	echo

}


file(){
queue=$1
	echo -e $BLANC"Nombre ticket cree pour la file $queue "$NORMAL;	
	# Total de ticket cree
	request="Queue = '$queue' AND Created >='$FIRSTDAYMONTH' AND Created <='$LASTDAYMONTH'" # on créé une variable car on a besoin à plusieurs endroits
	if [ "$debug" == "true" ]; then
		query="$VERT : Requete => \"$request\""
	else
		query=""
	fi
	echo -e "$VERT""Total : "$ROUGE"$(rt ls -i "$request" | grep ticket -c)"$query"$NORMAL";
	unset request # on detruit la variable pour eviter les problemes

	# Total de ticket cree par la tg
	request="Queue = '$queue' AND $cTg AND Created >='$FIRSTDAYMONTH' AND Created <='$LASTDAYMONTH'" 	
        if [ "$debug" == "true" ]; then
                query="$VERT : Requete => \"$request\""
        else
                query=""
        fi
	echo -e "$ROSE""Total pour la telegestion : "$ROUGE"$(rt ls -i "$request" | grep ticket -c)"$query"$NORMAL";
	unset request

	# Total de ticket cree par le giprecia
	request="Queue = '$queue' AND $cRecia AND Created >='$FIRSTDAYMONTH' AND Created <='$LASTDAYMONTH'"
        if [ "$debug" == "true" ]; then
                query="$VERT : Requete => \"$request\""
        else
                query=""
        fi
	echo -e "$JAUNE""Total pour le giprecia : "$ROUGE"$(rt ls -i "$request" | grep ticket -c)"$query"$NORMAL";
	unset request

        # Total de ticket cree par reciabot
	request="Queue = '$queue' AND $cBot AND Created >='$FIRSTDAYMONTH' AND Created <='$LASTDAYMONTH'"
        if [ "$debug" == "true" ]; then
                query="$VERT : Requete => \"$request\""
        else
                query=""
        fi
        echo -e "$BLEU""Total cree automatiquement (reciabot + root) : "$ROUGE"$(rt ls -i "$request" | grep ticket -c)"$query"$NORMAL";
	unset request

        # Total de ticket cree par les admins
	request="Queue = '$queue' AND $cOther AND Created >='$FIRSTDAYMONTH' AND Created <='$LASTDAYMONTH'"
        if [ "$debug" == "true" ]; then
                query="$VERT : Requete => \"$request\""
        else
                query=""
        fi
        echo -e "$CYAN""Total pour les admins : "$ROUGE"$(rt ls -i "$request" | grep ticket -c)"$query"$NORMAL";
	unset request

	echo
        echo -e $BLANC"Nombre ticket resolu pour la file $queue "$NORMAL;

        # Total de ticket resolu
	request="Queue = '$queue' AND Resolved >='$FIRSTDAYMONTH' AND Resolved <='$LASTDAYMONTH'"
        if [ "$debug" == "true" ]; then
                query="$VERT : Requete => \"$request\""
        else
                query=""
        fi
	echo -e "$VERT""Total : "$ROUGE"$(rt ls -i "$request" | grep ticket -c)"$query"$NORMAL";
	unset request

        # Total de ticket resolu par la telegestion
	request="Queue = '$queue' AND $oTg AND Resolved >='$FIRSTDAYMONTH' AND Resolved <='$LASTDAYMONTH'"
        if [ "$debug" == "true" ]; then
                query="$VERT : Requete => \"$request\""
        else
                query=""
        fi
        echo -e "$ROSE""Total pour la telegestion : "$ROUGE"$(rt ls -i "$request" | grep ticket -c)"$query"$NORMAL";
	unset request

        # Total de ticket resolu par le giprecia
	request="Queue = '$queue' AND $oRecia AND Resolved >='$FIRSTDAYMONTH' AND Resolved <='$LASTDAYMONTH'"
        if [ "$debug" == "true" ]; then
                query="$VERT : Requete => \"$request\""
        else
                query=""
        fi
        echo -e "$JAUNE""Total pour le giprecia : "$ROUGE"$(rt ls -i "$request" | grep ticket -c)"$query"$NORMAL";
	unset request

        # Total de ticket resolu en nobody
	request="Queue = '$queue' AND Owner = 'nobody' AND Resolved >='$FIRSTDAYMONTH' AND Resolved <='$LASTDAYMONTH'"
        if [ "$debug" == "true" ]; then
                query="$VERT : Requete => \"$request\""
        else
                query=""
        fi
        echo -e "$BLEU""Total pour Nobody : "$ROUGE"$(rt ls -i "$request" | grep ticket -c)"$query"$NORMAL";
	unset request

	echo
        echo -e $BLANC"Nombre ticket pere resolu pour la file $queue "$NORMAL;

        # Total de ticket pere resolu
	request="Queue = '$queue' AND MemberOf IS NULL AND Resolved >='$FIRSTDAYMONTH' AND Resolved <='$LASTDAYMONTH'"
        if [ "$debug" == "true" ]; then
                query="$VERT : Requete => \"$request\""
        else
                query=""
        fi
        echo -e "$VERT""Total : "$ROUGE"$(rt ls -i "$request" | grep ticket -c)"$query"$NORMAL";
	unset request

        # Total de ticket resolu par la telegestion
	request="Queue = '$queue' AND MemberOf IS NULL AND $oTg AND Resolved >='$FIRSTDAYMONTH' AND Resolved <='$LASTDAYMONTH'"
        if [ "$debug" == "true" ]; then
                query="$VERT : Requete => \"$request\""
        else
                query=""
        fi
        echo -e "$ROSE""Total pour la telegestion : "$ROUGE"$(rt ls -i "$request" | grep ticket -c)"$query"$NORMAL";
	unset request

        # Total de ticket resolu par le giprecia
	request="Queue = '$queue' AND MemberOf IS NULL AND $oRecia AND Resolved >='$FIRSTDAYMONTH' AND Resolved <='$LASTDAYMONTH'"
        if [ "$debug" == "true" ]; then
                query="$VERT : Requete => \"$request\""
        else
                query=""
        fi
        echo -e "$JAUNE""Total pour le giprecia : "$ROUGE"$(rt ls -i "$request" | grep ticket -c)"$query"$NORMAL";
	unset request

        # Total de ticket resolu en nobody
	request="Queue = '$queue' AND MemberOf IS NULL AND Owner = 'nobody' AND Resolved >='$FIRSTDAYMONTH' AND Resolved <='$LASTDAYMONTH'"
        if [ "$debug" == "true" ]; then
                query="$VERT : Requete => \"$request\""
        else
                query=""
        fi
        echo -e "$BLEU""Total pour Nobody : "$ROUGE"$(rt ls -i "$request" | grep ticket -c)"$query"$NORMAL";
	unset request
	echo
}


# Pas de paramètre on lance l'usage
[[ $# -lt 1 ]] && usage && exit 0

# on verifie les options
while getopts "edvh-:m:a:" opt ; do
        if [ $opt = "-" ] ; then
                case $OPTARG in
                        help ) opt="h" ;;
                        version ) opt="v" ;;
			mois ) opt="m" ;;
			annee ) opt="a" ;;
                        debug ) opt="d" ;;
                        export ) opt="e" ;;
                        * )
                            echo "Option longue inconnue..."
                            break ;;
                esac
        fi
        case $opt in
                h ) usage ;;
                v ) echo "Version 0.1" ;;
		m ) 
		    if [ -n $OPTARG ];
		    then
			month="$OPTARG" 
		    fi;;
		a ) 
		   if [ -n $OPTARG ];
                   then
                        year="$OPTARG"
                   fi;;
                d ) debug="true" ;;
                e ) expor="true" ;;
                ? ) echo "Option inconnue" ;;
        esac
done

if [ ! -z $month ] && [ ! -z $year ]
then
	if [ "$expor" == "true" ]; then
		export
	else
		traitement
	fi
fi
if [ -z $month ] || [ -z $year ]; then
        echo "Erreur : Le parametre -m ou -a ne sont pas mentionnes" && exit 1
fi
