#!/usr/bin/expect
set timeout 20
set name [lindex $argv 0]
set user [lindex $argv 1]
set password [lindex $argv 2]
spawn telnet $name
expect "$user:"
send "$user\r"
expect "Password:"
send "$password\r"
interact 
